# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13BfI746uujUIO7rDfpZx_tRShu1ot2OX
"""

import sqlite3

dbname="jobinfo"

conn=sqlite3.connect(dbname+".db")

import pandas as pd
import numpy as np

df=pd.read_excel("Job_info_app.xlsx",engine='openpyxl')

df.columns

newname=df.rename(columns={"JOB Title":"Exam","Exam conducting body":"Organisation","Minimum Qualification":"Qualification",'Salary Range':"Salary",'minimum age':"Minage",'maximum age':"Maxage",'caste based allowance':"Allowance",'MODE OF EXAMINATION':"ExamMode","APPLICATION FEE":"Fee","Stages":"Level",'PHYSICAL TEST ':"Ptest","OFFICIAL WEBSITE":"Website","FIELD OF EXAM":"Fields","ATTEMPTS":"Attempts",'HANDICAPPED-ATTEMPTS':"Pattempts"})

newname.columns

newname.to_csv("exams.csv")



dfg=pd.read_csv("exams.csv")

dfg.columns

dfg['Minage']=dfg['Minage'].replace("NIL",0)
dfg["Maxage"]=dfg["Maxage"].replace("NIL",0)
dfg["Maxage"]=dfg["Maxage"].replace("na",0)
dfg["Minage"]=dfg['Minage'].fillna(0)
dfg["Maxage"]=dfg["Maxage"].fillna(0)

dfg=dfg.drop("Unnamed: 0",1)



dfg['Maxage']

dfg.astype({"Minage":"int64"}).dtypes
dfg.astype({"Maxage":"int64"}).dtypes

dfg.dtypes

dfg.dtypes



dfg.to_sql(name="Table1",con=conn,if_exists="append")

cns=sqlite3.connect("jobinfo.db")

crsc=cns.cursor()

crsc.execute("SELECT * FROM Table1")

ans=crsc.description

for x in ans:
  print(x)

